package com.gadarts.dte

enum class EditorEvents {
    LAYER_ADDED,
    LAYER_SELECTED,
    OBJECT_SELECTED,
    MODE_CHANGED,
    BUTTON_PRESSED_ROTATE_CLOCKWISE,
    BUTTON_PRESSED_ROTATE_COUNTER_CLOCKWISE,
    GRID_SET
}
