package com.gadarts.returnfire.systems.events

enum class SystemEvents {
    CHARACTER_WEAPON_ENGAGED_PRIMARY,
    CHARACTER_WEAPON_ENGAGED_SECONDARY,
    CHARACTER_DIED,
    CHARACTER_ONBOARDED,
    CHARACTER_BOARDING,
    CHARACTER_ONBOARDING_ANIMATION_DONE,
    BUTTON_WEAPON_PRIMARY_PRESSED,
    BUTTON_WEAPON_PRIMARY_RELEASED,
    BUTTON_WEAPON_SECONDARY_PRESSED,
    BUTTON_WEAPON_SECONDARY_RELEASED,
    BUTTON_REVERSE_PRESSED,
    BUTTON_REVERSE_RELEASED,
    BUTTON_ONBOARD_PRESSED,
    PHYSICS_SYSTEM_READY,
    PHYSICS_COMPONENT_ADDED_MANUALLY,
    PHYSICS_COMPONENT_REMOVED_MANUALLY,
    PHYSICS_COLLISION,
    PHYSICS_DROWNING,
    BULLET_CREATION_REQUEST,
    CONSOLE_COMMAND_EXECUTED,
    LANDING_INDICATOR_VISIBILITY_CHANGED,
    AMB_SOUND_COMPONENT_ADDED,
    PLAYER_ADDED,
    OPPONENT_CHARACTER_CREATED,
    MAP_LOADED
}
