package com.gadarts.returnfire.systems.events

enum class SystemEvents {
    CHARACTER_WEAPON_ENGAGED_PRIMARY,
    CHARACTER_WEAPON_ENGAGED_SECONDARY,
    WEAPON_BUTTON_PRIMARY_PRESSED,
    WEAPON_BUTTON_PRIMARY_RELEASED,
    WEAPON_BUTTON_SECONDARY_PRESSED,
    WEAPON_BUTTON_SECONDARY_RELEASED,
    PHYSICS_SYSTEM_READY,
    PHYSICS_COMPONENT_ADDED_MANUALLY,
    PHYSICS_COLLISION,
    BULLET_CREATION_REQUEST

}
