package com.gadarts.returnfire.systems

enum class SystemEvents {
    PLAYER_WEAPON_SHOT,
    PLAYER_ENTERED_NEW_REGION,
    WEAPON_BUTTON_PRIMARY_PRESSED,
    WEAPON_BUTTON_PRIMARY_RELEASED,
    WEAPON_BUTTON_SECONDARY_PRESSED,
    WEAPON_BUTTON_SECONDARY_RELEASED


}
