package com.gadarts.returnfire.systems.map

import com.gadarts.returnfire.assets.definitions.TextureDefinition

object TilesMapping {
    val tiles = listOf(
        TextureDefinition.TILE_WATER,
        TextureDefinition.TILE_BEACH_BOTTOM_RIGHT,
        TextureDefinition.TILE_BEACH_GULF_BOTTOM_RIGHT,
        TextureDefinition.TILE_BEACH_BOTTOM,
        TextureDefinition.TILE_BEACH_BOTTOM_SPECIAL,
        TextureDefinition.TILE_BEACH_BOTTOM_LEFT,
        TextureDefinition.TILE_BEACH_GULF_BOTTOM_LEFT,
        TextureDefinition.TILE_BEACH_RIGHT,
        TextureDefinition.TILE_BEACH_LEFT,
        TextureDefinition.TILE_BEACH_TOP_RIGHT,
        TextureDefinition.TILE_BEACH_GULF_TOP_RIGHT,
        TextureDefinition.TILE_BEACH_TOP,
        TextureDefinition.TILE_BEACH_TOP_LEFT,
        TextureDefinition.TILE_BEACH_GULF_TOP_LEFT,
        TextureDefinition.TILE_BEACH,
        TextureDefinition.TILE_WATER_SHALLOW_BOTTOM_RIGHT,
        TextureDefinition.TILE_WATER_SHALLOW_GULF_BOTTOM_RIGHT,
        TextureDefinition.TILE_WATER_SHALLOW_BOTTOM,
        TextureDefinition.TILE_WATER_SHALLOW_BOTTOM_LEFT,
        TextureDefinition.TILE_WATER_SHALLOW_GULF_BOTTOM_LEFT,
        TextureDefinition.TILE_WATER_SHALLOW_RIGHT,
        TextureDefinition.TILE_WATER_SHALLOW_LEFT,
        TextureDefinition.TILE_WATER_SHALLOW_TOP_RIGHT,
        TextureDefinition.TILE_WATER_SHALLOW_GULF_TOP_RIGHT,
        TextureDefinition.TILE_WATER_SHALLOW_TOP,
        TextureDefinition.TILE_WATER_SHALLOW_TOP_LEFT,
        TextureDefinition.TILE_WATER_SHALLOW_GULF_TOP_LEFT,
        TextureDefinition.TILE_WATER_SHALLOW,
        TextureDefinition.TILE_BEACH_ROAD_HORIZONTAL,
        TextureDefinition.TILE_BEACH_ROAD_HORIZONTAL_TOP,
        TextureDefinition.TILE_BEACH_ROAD_HORIZONTAL_BOTTOM,
        TextureDefinition.TILE_BEACH_ROAD_HORIZONTAL_END_RIGHT,
        TextureDefinition.TILE_BEACH_ROAD_HORIZONTAL_END_LEFT,
        TextureDefinition.TILE_BEACH_ROAD_VERTICAL,
        TextureDefinition.TILE_BEACH_ROAD_VERTICAL_RIGHT,
        TextureDefinition.TILE_BEACH_ROAD_VERTICAL_LEFT,
        TextureDefinition.TILE_BEACH_ROAD_VERTICAL_END_UP,
        TextureDefinition.TILE_BEACH_ROAD_VERTICAL_END_DOWN,
        TextureDefinition.TILE_BEACH_ROAD_BOTTOM_RIGHT,
        TextureDefinition.TILE_BEACH_ROAD_BOTTOM_LEFT,
        TextureDefinition.TILE_BEACH_ROAD_TOP_LEFT,
        TextureDefinition.TILE_BEACH_ROAD_TOP_RIGHT,
        TextureDefinition.TILE_BEACH_ROAD_CROSS,
        TextureDefinition.TILE_BEACH_GRASS,
        TextureDefinition.TILE_BEACH_GRASS_TOP,
        TextureDefinition.TILE_BEACH_GRASS_RIGHT,
        TextureDefinition.TILE_BEACH_GRASS_BOTTOM,
        TextureDefinition.TILE_BEACH_GRASS_LEFT,
        TextureDefinition.TILE_BEACH_GRASS_TOP_RIGHT,
        TextureDefinition.TILE_BEACH_GRASS_TOP_LEFT,
        TextureDefinition.TILE_BEACH_GRASS_BOTTOM_RIGHT,
        TextureDefinition.TILE_BEACH_GRASS_BOTTOM_LEFT,
        TextureDefinition.TILE_BEACH_GRASS_GULF_TOP_RIGHT,
        TextureDefinition.TILE_BEACH_GRASS_GULF_TOP_LEFT,
        TextureDefinition.TILE_BEACH_GRASS_GULF_BOTTOM_RIGHT,
        TextureDefinition.TILE_BEACH_GRASS_GULF_BOTTOM_LEFT,
        TextureDefinition.TILE_BEACH_DARK,
        TextureDefinition.TILE_BEACH_DARK_TOP,
        TextureDefinition.TILE_BEACH_DARK_RIGHT,
        TextureDefinition.TILE_BEACH_DARK_BOTTOM,
        TextureDefinition.TILE_BEACH_DARK_LEFT,
        TextureDefinition.TILE_BEACH_DARK_TOP_RIGHT,
        TextureDefinition.TILE_BEACH_DARK_TOP_LEFT,
        TextureDefinition.TILE_BEACH_DARK_BOTTOM_RIGHT,
        TextureDefinition.TILE_BEACH_DARK_BOTTOM_LEFT,
        TextureDefinition.TILE_BEACH_DARK_GULF_TOP_RIGHT,
        TextureDefinition.TILE_BEACH_DARK_GULF_TOP_LEFT,
        TextureDefinition.TILE_BEACH_DARK_GULF_BOTTOM_RIGHT,
        TextureDefinition.TILE_BEACH_DARK_GULF_BOTTOM_LEFT,
    )

}
